{% set name = "tudat" %}
  {% set version = "2.8.10" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/ggarrett13/tudat.git
  git_rev: 3a4608292cd3e0bbeaff7a5bd5be539dab76cb16

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 1
  skip: true  # [win and vc<14]


requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
    - cmake

build:
  run_exports:
    - tudat-cspice
    - tudat-sofa

outputs:
  - name: "{{ name }}"
    requirements:
      build:
        # Tools required to build the package. These packages are run on the build
        # system and include things such as revision control systems (Git, SVN) make
        # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
        # or native when not cross-compiling), and any source pre-processors.
        - boost-cpp==1.64.0
        - tudat-cspice
        - tudat-sofa
        #        - nlohmann_json
        - eigen


      host:
        # Packages that need to be specific to the target platform when the
        # target platform is not necessarily the same as the native build
        # platform
        - boost-cpp==1.64.0
        - tudat-cspice
        - tudat-sofa
        #        - nlohmann_json
        - eigen

      run:
        # Packages required to run the package. These are the dependencies
        # that are installed automatically whenever the package is installed.
        # Package names should follow the package match specifications.
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}


        #    files:
        # Explicit file lists are relative paths from the root of the build
        # prefix. Explicit file lists support glob expressions. Directory
        # names are also supported, and they recursively include contents.
        #      - lib/libtudat*{{ SHLIB_EXT }}   # [not win]
        #      - lib/libtudat.so.*              # [linux]
        #      - lib/libpagmo.*.dylib           # [osx]
        #      - Library/bin/tudat.dll          # [win]
        #
        #    - name: tudat-devel
        #      build:
        #        run_exports:
        #          # Some build or host Requirements section will impose a runtime
        #          # requirement. Most commonly this is true for shared libraries
        #          # (e.g. libpng), which are required for linking at build time, and
        #          # for resolving the link at run time.
        ##          - {{ pin_subpackage('tudat', max_pin='x.x') }}
        #  #        - {{ pin_compatible('boost', max_pin='x.x') }}
        #  #        - {{ pin_compatible('nlopt', max_pin='x.x') }}
        ##          - {{ pin_compatible('cspice', max_pin='x.x') }}
        #  #        - {{ pin_compatible('pagmo-devel', max_pin='x.x') }}
        #      requirements:
        #        host:
        #          - boost-cpp
        #  #        - eigen
        #  #        - nlopt
        #
        #  #        - tbb-devel
        #  #        - pagmo-devel
        #        run:
        #          - {{ pin_subpackage("{{ name }}", exact=True) }}
        #          - boost-cpp
        #        - eigen

        #        - tbb-devel
        #        - pagmo-devel
        #      files:
        # Explicit file lists are relative paths from the root of the build
        # prefix. Explicit file lists support glob expressions. Directory
        # names are also supported, and they recursively include contents.
  #      - lib/libtudat*{{ SHLIB_EXT }}   # [not win]
  #      - lib/libtudat.so.*              # [linux]
  #      - lib/libpagmo.*.dylib           # [osx]
  #      - Library/bin/tudat.dll          # [win]


about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: Tudat Bundle packs Tudat and external libraries in a modular fashion
